const form = document.querySelector('#chatForm');
const input = document.querySelector('#messageInput');
const messages = document.querySelector('#messages');
const voiceBtn = document.querySelector('#voiceBtn');
const clearBtn = document.querySelector('#clearBtn');
const statusText = document.querySelector('#statusText');

function addMessage(text, role) {
  const article = document.createElement('article');
  article.className = `message ${role}`;
  const avatar = document.createElement('div');
  avatar.className = 'avatar';
  avatar.textContent = role === 'assistant' ? 'U' : 'Y';
  const wrap = document.createElement('div');
  wrap.className = 'bubble-wrap';
  const speaker = document.createElement('span');
  speaker.className = 'speaker';
  speaker.textContent = role === 'assistant' ? 'ULTRON' : 'YOU';
  const time = document.createElement('time');
  time.textContent = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  speaker.append(' ', time);
  const bubble = document.createElement('div');
  bubble.className = 'bubble';
  bubble.textContent = text;
  wrap.append(speaker, bubble);
  article.append(avatar, wrap);
  messages.append(article);
  messages.scrollTop = messages.scrollHeight;
}

function demoReply(text) {
  const normalized = text.toLowerCase();
  if (/\b(hello|hi|hey)\b/.test(normalized)) return 'Greetings. ULTRON interface is responding. My live AI brain is not connected yet, so this is a local demo response.';
  if (normalized.includes('who are you') || normalized.includes('what are you')) return "I am ULTRON, a personal AI assistant project. Right now, you're interacting with the front-end demo—not a live AI model.";
  if (normalized.includes('help')) return 'You can type a message, press Send, or try the microphone button if your browser supports speech recognition. A secure backend still needs to be connected for real AI conversations.';
  if (normalized.includes('voice')) return 'The voice controls use browser speech features when supported. The voice is generated by your device/browser, not by a connected AI service.';
  return 'Message received. This is demo mode, so I can’t reason over your message with a live AI model yet. The next milestone is connecting a backend while keeping API credentials off the public-facing page.';
}

form.addEventListener('submit', (event) => {
  event.preventDefault();
  const text = input.value.trim();
  if (!text) return;
  addMessage(text, 'user');
  input.value = '';
  addMessage(demoReply(text), 'assistant');
});

input.addEventListener('keydown', (event) => {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault();
    form.requestSubmit();
  }
});

clearBtn.addEventListener('click', () => {
  messages.replaceChildren();
  addMessage("Conversation cleared. I'm standing by in demo mode.", 'assistant');
});

let recognition = null;
const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
if (SpeechRecognition) {
  recognition = new SpeechRecognition();
  recognition.lang = navigator.language || 'en-US';
  recognition.interimResults = false;
  recognition.continuous = false;
  recognition.addEventListener('start', () => {
    voiceBtn.classList.add('listening');
    voiceBtn.setAttribute('aria-label', 'Stop voice input');
    statusText.textContent = 'MICROPHONE LISTENING';
  });
  recognition.addEventListener('result', (event) => {
    const transcript = event.results?.[0]?.[0]?.transcript;
    if (transcript) {
      input.value = transcript;
      input.focus();
    }
  });
  recognition.addEventListener('error', () => {
    statusText.textContent = 'VOICE INPUT UNAVAILABLE';
  });
  recognition.addEventListener('end', () => {
    voiceBtn.classList.remove('listening');
    voiceBtn.setAttribute('aria-label', 'Start voice input');
    statusText.textContent = 'SYSTEM ONLINE · DEMO MODE';
  });
}

voiceBtn.addEventListener('click', () => {
  if (!recognition) {
    addMessage('Speech recognition is not supported in this browser. You can still type messages.', 'assistant');
    return;
  }
  try {
    recognition.start();
  } catch (error) {
    statusText.textContent = 'VOICE INPUT ALREADY ACTIVE';
  }
});
