const form=document.querySelector('#chatForm'),input=document.querySelector('#messageInput'),messages=document.querySelector('#messages'),voiceBtn=document.querySelector('#voiceBtn'),clearBtn=document.querySelector('#clearBtn'),statusText=document.querySelector('#statusText'),statusDot=document.querySelector('#statusDot'),systemNote=document.querySelector('#systemNote'),modelState=document.querySelector('#modelState'),sendBtn=document.querySelector('.send-btn'),API_URL=window.ULTRON_API_URL||'';

function addMessage(text,role,typing=false){const a=document.createElement('article');a.className=`message ${role}${typing?' typing':''}`;const av=document.createElement('div');av.className='avatar';av.textContent=role==='assistant'?'U':'Y';const w=document.createElement('div');w.className='bubble-wrap';const s=document.createElement('span');s.className='speaker';s.textContent=role==='assistant'?'ULTRON':'YOU';const t=document.createElement('time');t.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});s.append(' ',t);const b=document.createElement('div');b.className='bubble';b.textContent=text;w.append(s,b);a.append(av,w);messages.append(a);messages.scrollTop=messages.scrollHeight;return a}
async function askUltron(text){if(!API_URL)throw new Error('Backend URL is not configured.');const r=await fetch(API_URL+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,max_tokens:160,temperature:.8})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'ULTRON server error');return d.reply}
async function updateConnectionStatus(){if(!API_URL){statusText.textContent='BACKEND NOT CONFIGURED';statusDot.className='';systemNote.textContent='WAITING FOR NEURAL CORE CONNECTION';modelState.textContent='MODEL READY · SERVER PENDING';return}try{const r=await fetch(API_URL+'/health');if(!r.ok)throw Error();statusText.textContent='SYSTEM ONLINE · ULTRON v0.2';statusDot.className='online';systemNote.textContent='NEURAL CORE ONLINE';modelState.textContent='MODEL ONLINE'}catch{statusText.textContent='SERVER OFFLINE';statusDot.className='offline';systemNote.textContent='NEURAL CORE OFFLINE';modelState.textContent='MODEL READY · SERVER OFFLINE'}}
async function sendMessage(text){addMessage(text,'user');input.value='';const thinking=addMessage('···','assistant',true);sendBtn.disabled=true;try{const reply=await askUltron(text);thinking.classList.remove('typing');thinking.querySelector('.bubble').textContent=reply}catch(e){thinking.classList.remove('typing');thinking.querySelector('.bubble').textContent='I cannot reach my neural core right now. The server connection needs attention.';statusText.textContent='SERVER OFFLINE'}finally{sendBtn.disabled=false;input.focus()}}
form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(text)sendMessage(text)});
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
clearBtn.addEventListener('click',()=>{messages.replaceChildren();addMessage('Conversation cleared. Neural core standing by.','assistant')});
document.querySelectorAll('.quick-card').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.prompt;input.focus()}));
let recognition=null;const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang=navigator.language||'en-US';recognition.interimResults=false;recognition.continuous=false;recognition.addEventListener('start',()=>{voiceBtn.classList.add('listening');voiceBtn.setAttribute('aria-label','Stop voice input');statusText.textContent='MICROPHONE LISTENING'});recognition.addEventListener('result',e=>{const tr=e.results?.[0]?.[0]?.transcript;if(tr){input.value=tr;input.focus()}});recognition.addEventListener('error',()=>{statusText.textContent='VOICE INPUT UNAVAILABLE'});recognition.addEventListener('end',()=>{voiceBtn.classList.remove('listening');voiceBtn.setAttribute('aria-label','Start voice input');updateConnectionStatus()})}
voiceBtn.addEventListener('click',()=>{if(!recognition){addMessage('Speech recognition is not supported in this browser. You can still type messages.','assistant');return}try{recognition.start()}catch{statusText.textContent='VOICE INPUT ALREADY ACTIVE'}});
updateConnectionStatus();
